<?xml version="1.0"?>
<!DOCTYPE stencil [
<!ELEMENT stencil (#PCDATA | items)*>
<!ATTLIST stencil
name CDATA #REQUIRED
tabname CDATA #REQUIRED
>
<!ELEMENT items (#PCDATA | item)*>
<!ELEMENT item (#PCDATA | tags)*>
<!ATTLIST item
type CDATA #REQUIRED
shortcut CDATA #REQUIRED
label CDATA #REQUIRED
tooltip CDATA #REQUIRED
image CDATA #REQUIRED
paletteimage CDATA #REQUIRED
backgroundimage CDATA #IMPLIED
template CDATA #IMPLIED
>
<!ELEMENT tags (#PCDATA | tag)*>
<!ELEMENT tag (#PCDATA)>
<!ATTLIST tag
id CDATA #REQUIRED
author CDATA #REQUIRED
created CDATA #REQUIRED
lastModified CDATA #REQUIRED
name CDATA #REQUIRED
description CDATA #REQUIRED
behavior CDATA #REQUIRED
>
]>

<stencil name="Approaches to LD: Examples of approaches to learning design - each map shows a different approach to the design process" tabname="Approaches to LD">
	<items>
		<item label="Step-by-Step" tooltip="A. Step-by-Step design guide and checklist" image="map.png" paletteimage="step-by-step.png" backgroundimage="design process bkg 2.png" template="step-by-step-guide-2.xml" shortcut="-1" type="2">
		</item>
		<item label="Simple mapping" tooltip="B. Simple mapping: tasks, assessments, learning outcomes" image="map.png" paletteimage="simple-mapping.png" backgroundimage="" template="simple-mapping.xml" shortcut="-1" type="2">
		</item>
		<item label="Mapping" tooltip="C. Mapping: learning outcomes, topics, tasks, problems, and assessment" image="map.png" paletteimage="mapping.png" backgroundimage="" template="mapping.xml" shortcut="-1" type="2">
		</item>
		<item label="Tool affordances" tooltip="D. Map of tools and affordances" image="map.png" paletteimage="tool-afford.png" backgroundimage="" template="tool-afford.xml" shortcut="-1" type="2">
		</item>
		<item label="Task affordance" tooltip="E. Map of tasks and affordances" image="map.png" paletteimage="task-afford.png" backgroundimage="" template="task-afford.xml" shortcut="-1" type="2">
		</item>
	</items>
</stencil>
