<?xml version="1.0"?>
<!DOCTYPE stencil [
<!ELEMENT stencil (#PCDATA | items)*>
<!ATTLIST stencil
name CDATA #REQUIRED
tabname CDATA #REQUIRED
>
<!ELEMENT items (#PCDATA | item)*>
<!ELEMENT item (#PCDATA | tags)*>
<!ATTLIST item
type CDATA #REQUIRED
shortcut CDATA #REQUIRED
label CDATA #REQUIRED
tooltip CDATA #REQUIRED
image CDATA #REQUIRED
paletteimage CDATA #REQUIRED
backgroundimage CDATA #IMPLIED
template CDATA #IMPLIED
>
<!ELEMENT tags (#PCDATA | tag)*>
<!ELEMENT tag (#PCDATA)>
<!ATTLIST tag
id CDATA #REQUIRED
author CDATA #REQUIRED
created CDATA #REQUIRED
lastModified CDATA #REQUIRED
name CDATA #REQUIRED
description CDATA #REQUIRED
behavior CDATA #REQUIRED
>
]>

<stencil name="LD-OU" tabname="LD-OU">
	<items>
		<item label="Activity" tooltip="Activity" image="id_activity.png" paletteimage="id_activity_toolbar.png" backgroundimage="" template="" shortcut="1" type="2">
			<tags>
				<tag id="169254221183024392174" author="No Description" created="1183024392174" lastModified="1183024392174" name="^_ld^activity_^" description="No Behavior" behavior="Administrator"/>
			</tags>
		</item>
		<item label="Learner output" tooltip="Learner output for formative or summative assessment" image="id_assessment.png" paletteimage="" backgroundimage="" template="" shortcut="2" type="9">
			<tags>
				<tag id="137108541361214844172527" author="No Behavior" created="1214844172527" lastModified="1214844172527" name="^_ld^assessment_^" description="Administrator" behavior="No Description"/>
			</tags>
		</item>
		<item label="Learning outcome" tooltip="Learning outcome" image="id_learning-outcome.png" paletteimage="" backgroundimage="" template="" shortcut="3" type="9">
			<tags>
				<tag id="137108541361214844076984" author="No Behavior" created="1214844076984" lastModified="1214844076984" name="^_ld^learning_outcome_^" description="Administrator" behavior="No Description"/>
			</tags>
		</item>
		<item label="Resource" tooltip="Resource" image="id_resource.png" paletteimage="id_resource_toolbar.png" backgroundimage="" template="" shortcut="4" type="9">
			<tags>
				<tag id="169254221183024509828" author="No Description" created="1183024509828" lastModified="1183024509828" name="^_ld^resource_^" description="No Behavior" behavior="Administrator"/>
			</tags>
		</item>
		<item label="Role" tooltip="Role" image="id_role.png" paletteimage="id_role_toolbar.png" backgroundimage="" template="" shortcut="5" type="9">
			<tags>
				<tag id="169254221183024535695" author="No Description" created="1183024535695" lastModified="1183024535695" name="^_ld^role_^" description="No Behavior" behavior="Administrator"/>
			</tags>
		</item>
		<item label="Stop" tooltip="Stop" image="id_stop.png" paletteimage="id_stop_toolbar.png" backgroundimage="" template="" shortcut="6" type="9">
			<tags>
				<tag id="137108541361201188198715" author="No Behavior" created="1201188198715" lastModified="1201188198715" name="^_ld^stop_^" description="Administrator" behavior="No Description"/>
			</tags>
		</item>
		<item label="Task" tooltip="Task" image="id_task.png" paletteimage="id_task_toolbar.png" backgroundimage="" template="" shortcut="7" type="9">
			<tags>
				<tag id="137108541361182247437407" author="No Description" created="1182247437407" lastModified="1182247437407" name="^_ld^task_^" description="No Behavior" behavior="Administrator"/>
			</tags>
		</item>
		<item label="Tool" tooltip="Tool" image="id_tool.png" paletteimage="id_tool_toolbar.png" backgroundimage="" template="" shortcut="8" type="9">
			<tags>
				<tag id="169254221183024627481" author="No Description" created="1183024627481" lastModified="1183024627481" name="^_ld^vle^tool_^" description="No Behavior" behavior="Administrator"/>
			</tags>
		</item>
	</items>
</stencil>
