<?xml version="1.0"?>
<!DOCTYPE stencil [
<!ELEMENT stencil (#PCDATA | items)*>
<!ATTLIST stencil
name CDATA #REQUIRED
tabname CDATA #REQUIRED
>
<!ELEMENT items (#PCDATA | item)*>
<!ELEMENT item (#PCDATA | tags)*>
<!ATTLIST item
type CDATA #REQUIRED
shortcut CDATA #REQUIRED
label CDATA #REQUIRED
tooltip CDATA #REQUIRED
image CDATA #REQUIRED
paletteimage CDATA #REQUIRED
backgroundimage CDATA #IMPLIED
template CDATA #IMPLIED
>
<!ELEMENT tags (#PCDATA | tag)*>
<!ELEMENT tag (#PCDATA)>
<!ATTLIST tag
id CDATA #REQUIRED
author CDATA #REQUIRED
created CDATA #REQUIRED
lastModified CDATA #REQUIRED
name CDATA #REQUIRED
description CDATA #REQUIRED
behavior CDATA #REQUIRED
>
]>

<stencil name="Map outcomes to activities" tabname="Outcomes to activities">
	<items>
	
		<item label="Map outcomes to activities" tooltip="Map learning outcomes to activities" image="id_learning-outcome_activities_map.png" paletteimage="id_learning-outcome_activities_map.png" backgroundimage="" template="" shortcut="2" type="2">
		</item>
		
		<item label="Map outcomes to concepts" tooltip="Map learning outcomes to concepts" image="learning_outcome-to-concept.png" paletteimage="learning_outcome-to-concept.png" backgroundimage="" template="" shortcut="3" type="2">
		</item>
		
		<item label="Learning outcome" tooltip="Specific example of a learning outcome" image="id_learning-outcome.png" paletteimage="id_learning-outcome.png" backgroundimage="" template="" shortcut="4" type="9">
			<tags>
				<tag id="137108541361214844076984" author="No Behavior" created="1214844076984" lastModified="1214844076984" name="^_ld^learning_outcome_^" description="Administrator" behavior="No Description"/>
			</tags>
		</item>
		
		<item label="Concept" tooltip="A concept the understanding of which is shown via learning outcomes" image="position.png" paletteimage="position.png" backgroundimage="" template="" shortcut="1" type="9">
		</item>
		
	</items>
	
</stencil>
